export const NOTIFICATION_TYPE = {
  ORGANIZATION_JOIN_APPROVED: 'ORGANIZATION_JOIN_APPROVED',
  ORGANIZATION_JOIN_REJECTED: 'ORGANIZATION_JOIN_REJECTED',
  ORGANIZATION_JOIN_REQUEST: 'ORGANIZATION_JOIN_REQUEST',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  REVIEW_AVAILABLE: 'REVIEW_AVAILABLE',
  REVIEW_APPROVED_BY_ALL: 'REVIEW_APPROVED_BY_ALL',
  REVIEW_REWORK_REQUIRED: 'REVIEW_REWORK_REQUIRED',
  THREAD_REPLY: 'THREAD_REPLY',
  TASK_COMPLETED_REVIEWER: 'TASK_COMPLETED_REVIEWER',
  TASK_COMPLETED_OWNER: 'TASK_COMPLETED_OWNER',
  ACHIEVEMENT_RECEIVED: 'ACHIEVEMENT_RECEIVED'
};

export const NOTIFICATION_COMPLETION_ACTION = {
  OPEN_ORGANIZATION: 'OPEN_ORGANIZATION',
  RESOLVE_ORGANIZATION_JOIN_REQUEST: 'RESOLVE_ORGANIZATION_JOIN_REQUEST',
  SUBMIT_TASK_SOLUTION: 'SUBMIT_TASK_SOLUTION',
  SUBMIT_REVIEW_RESULT: 'SUBMIT_REVIEW_RESULT',
  ACCEPT_REVIEW_RESULT: 'ACCEPT_REVIEW_RESULT',
  OPEN_TASK: 'OPEN_TASK',
  OPEN_REVIEW: 'OPEN_REVIEW',
  OPEN_LEADERBOARD: 'OPEN_LEADERBOARD',
  OPEN_PROFILE: 'OPEN_PROFILE'
};

export const NOTIFICATION_TTL_DAYS = {
  [NOTIFICATION_TYPE.ORGANIZATION_JOIN_APPROVED]: 3,
  [NOTIFICATION_TYPE.ORGANIZATION_JOIN_REJECTED]: 3,
  [NOTIFICATION_TYPE.ORGANIZATION_JOIN_REQUEST]: 5,
  [NOTIFICATION_TYPE.TASK_ASSIGNED]: 10,
  [NOTIFICATION_TYPE.REVIEW_AVAILABLE]: 10,
  [NOTIFICATION_TYPE.REVIEW_APPROVED_BY_ALL]: 7,
  [NOTIFICATION_TYPE.REVIEW_REWORK_REQUIRED]: 3,
  [NOTIFICATION_TYPE.THREAD_REPLY]: 3,
  [NOTIFICATION_TYPE.TASK_COMPLETED_REVIEWER]: 7,
  [NOTIFICATION_TYPE.TASK_COMPLETED_OWNER]: 3,
  [NOTIFICATION_TYPE.ACHIEVEMENT_RECEIVED]: 5
};

export const NOTIFICATION_TARGET_KIND = {
  ORGANIZATION: 'organization',
  TASK: 'task',
  REVIEW: 'review',
  LEADERBOARD: 'leaderboard',
  PROFILE: 'profile'
};
