export const SKILL_GROUPS = [
  {
    key: 'languages',
    title: 'Языки программирования:',
    options: [
      'C#',
      'Java',
      'Python',
      'JavaScript',
      'TypeScript',
      'Go',
      'Rust',
      'C++',
      'C',
      'PHP',
      'Ruby',
      'Swift',
      'Kotlin',
      'Scala',
      'Dart',
      'SQL',
    ],
  },
  {
    key: 'frameworks',
    title: 'Фреймворки и библиотеки:',
    options: [
      '.NET (Core / Framework)',
      'ASP.NET Core',
      'Entity Framework Core',
      'React',
      'Angular',
      'Vue.js',
      'Spring (Boot)',
      'Django',
      'Flask',
      'Express.js',
      'Node.js',
      'Ruby on Rails',
      'Laravel',
      'Flutter',
      'SwiftUI',
    ],
  },
  {
    key: 'tools',
    title: 'Инструменты и технологии:',
    options: [
      'Docker',
      'Kubernetes',
      'Git',
      'GitHub Actions',
      'Jenkins',
      'Terraform',
      'Ansible',
      'Prometheus',
      'Grafana',
      'Elastic Stack (ELK)',
    ],
  },
] as const;
