export const ORGANIZATION_MEMBER_ROLE = {
  OWNER: 'OWNER',
  MEMBER: 'MEMBER',
};

export const ORGANIZATION_MEMBER_ROLE_LABELS = {
  [ORGANIZATION_MEMBER_ROLE.OWNER]: 'Владелец',
  [ORGANIZATION_MEMBER_ROLE.MEMBER]: 'Участник',
};
