export const ROUTES = {
  home: '/',
  admin: '/admin',
  projects: '/projects',
  projectById: '/projects/:projectId',
  projectTaskCreate: '/projects/:projectId/tasks/create',
  projectTaskById: '/projects/:projectId/tasks/:taskId',
  reviewById: '/reviews/:reviewId',
  projectJoinByToken: '/projects/join/:token',
  organizationById: '/organizations/:organizationId',
  organizationJoinByToken: '/organizations/join/:token',
  reviews: '/reviews',
  leaderboard: '/leaderboard',
  profile: '/profile',
  profileByUserId: '/profile/:userId',
  login: '/login',
  register: '/register',
  recovery: '/recovery',
  verifyEmail: '/verify-email',
  resetPassword: '/reset-password'
};
