package ru.urfu.backend.model.enums;

public enum NotificationType {
    ORGANIZATION_JOIN_APPROVED,
    ORGANIZATION_JOIN_REJECTED,
    ORGANIZATION_JOIN_REQUEST,
    TASK_ASSIGNED,
    REVIEW_AVAILABLE,
    REVIEW_APPROVED_BY_ALL,
    REVIEW_REWORK_REQUIRED,
    REVIEW_EXPIRED_WITHOUT_DECISION,
    AI_REVIEW_COMPLETED,
    THREAD_REPLY,
    TASK_COMPLETED_REVIEWER,
    TASK_COMPLETED_OWNER,
    ACHIEVEMENT_RECEIVED
}
