export type Styles = {
  actions: string;
  bar: string;
  body: string;
  button: string;
  comment: string;
  content: string;
  content2: string;
  eyebrow: string;
  grid: string;
  icon: string;
  isAbout: string;
  isAccent: string;
  isAi: string;
  isBenefits: string;
  isCode: string;
  isGhost: string;
  isPrimary: string;
  isShort: string;
  isStacked: string;
  isSuccess: string;
  isThread: string;
  isWide: string;
  isWorkflow: string;
  item: string;
  item2: string;
  kicker: string;
  landingBenefits: string;
  landingButton: string;
  landingButtonPrimary: string;
  landingCta: string;
  landingFeatureCard: string;
  landingHero: string;
  landingHeroArt: string;
  landingPage: string;
  landingSection: string;
  landingSteps: string;
  lead: string;
  line: string;
  link: string;
  logo: string;
  logoLink: string;
  mark: string;
  nav: string;
  number: string;
  panel: string;
  root: string;
  sectionHeading: string;
  shell: string;
  text: string;
  text2: string;
  text3: string;
  title: string;
  title2: string;
  title3: string;
  title4: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
