export const ADMIN_EVENT_TYPE = {
  COMMENT_COMPLAINT_CREATED: 'COMMENT_COMPLAINT_CREATED',
  COMMENT_COMPLAINT_APPROVED: 'COMMENT_COMPLAINT_APPROVED',
  COMMENT_COMPLAINT_REJECTED: 'COMMENT_COMPLAINT_REJECTED',
  LEADERBOARD_RATING_RESET: 'LEADERBOARD_RATING_RESET',
  SYSTEM_REVIEW_DEADLINE_CHANGED: 'SYSTEM_REVIEW_DEADLINE_CHANGED',
  SYSTEM_AI_PROMPT_CHANGED: 'SYSTEM_AI_PROMPT_CHANGED'
};

export const ADMIN_EVENT_TYPE_LABELS = {
  [ADMIN_EVENT_TYPE.COMMENT_COMPLAINT_CREATED]: 'Поступление жалобы',
  [ADMIN_EVENT_TYPE.COMMENT_COMPLAINT_APPROVED]: 'Жалоба подтверждена',
  [ADMIN_EVENT_TYPE.COMMENT_COMPLAINT_REJECTED]: 'Жалоба отклонена',
  [ADMIN_EVENT_TYPE.LEADERBOARD_RATING_RESET]: 'Обнуление рейтинга',
  [ADMIN_EVENT_TYPE.SYSTEM_REVIEW_DEADLINE_CHANGED]: 'Срок ревью изменен',
  [ADMIN_EVENT_TYPE.SYSTEM_AI_PROMPT_CHANGED]: 'Системный промпт изменен'
};

export const ADMIN_EVENT_TYPE_OPTIONS = [
  { value: '', label: 'Все события' },
  { value: ADMIN_EVENT_TYPE.COMMENT_COMPLAINT_CREATED, label: ADMIN_EVENT_TYPE_LABELS[ADMIN_EVENT_TYPE.COMMENT_COMPLAINT_CREATED] },
  { value: ADMIN_EVENT_TYPE.COMMENT_COMPLAINT_APPROVED, label: ADMIN_EVENT_TYPE_LABELS[ADMIN_EVENT_TYPE.COMMENT_COMPLAINT_APPROVED] },
  { value: ADMIN_EVENT_TYPE.COMMENT_COMPLAINT_REJECTED, label: ADMIN_EVENT_TYPE_LABELS[ADMIN_EVENT_TYPE.COMMENT_COMPLAINT_REJECTED] },
  { value: ADMIN_EVENT_TYPE.LEADERBOARD_RATING_RESET, label: ADMIN_EVENT_TYPE_LABELS[ADMIN_EVENT_TYPE.LEADERBOARD_RATING_RESET] },
  { value: ADMIN_EVENT_TYPE.SYSTEM_REVIEW_DEADLINE_CHANGED, label: ADMIN_EVENT_TYPE_LABELS[ADMIN_EVENT_TYPE.SYSTEM_REVIEW_DEADLINE_CHANGED] },
  { value: ADMIN_EVENT_TYPE.SYSTEM_AI_PROMPT_CHANGED, label: ADMIN_EVENT_TYPE_LABELS[ADMIN_EVENT_TYPE.SYSTEM_AI_PROMPT_CHANGED] }
];

export const ADMIN_COMPLAINT_DECISION = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT'
};

export const ADMIN_COMPLAINT_PENALTY_POINTS = 100;
