export type Styles = {
  actionButton: string;
  aiCheck: string;
  assigneeAvatar: string;
  assigneeMore: string;
  assignees: string;
  content: string;
  content2: string;
  controls: string;
  controlsLeft: string;
  controlsRight: string;
  deadline: string;
  description: string;
  descriptionLabel: string;
  descriptionToggle: string;
  emptyState: string;
  info: string;
  isActive: string;
  isCancel: string;
  isDanger: string;
  isDone: string;
  isError: string;
  isHead: string;
  isInProgress: string;
  isInReview: string;
  isMine: string;
  isPrimary: string;
  isRework: string;
  isSave: string;
  isSuccess: string;
  isWarning: string;
  listEmpty: string;
  loader: string;
  metricItem: string;
  metrics: string;
  modeButton: string;
  modeSwitch: string;
  modeThumb: string;
  myTasks: string;
  organization: string;
  participantAvatar: string;
  participantLogin: string;
  participantMain: string;
  participantMeta: string;
  participantName: string;
  participantRole: string;
  participantRow: string;
  participantsCount: string;
  participantsList: string;
  privacyItem: string;
  privacyRow: string;
  privateIcon: string;
  repository: string;
  roleTag: string;
  root: string;
  searchField: string;
  sectionCard: string;
  sentinel: string;
  settings: string;
  settingsAction: string;
  settingsActions: string;
  settingsError: string;
  settingsField: string;
  settingsInput: string;
  settingsInputError: string;
  settingsTextarea: string;
  settingsTitle: string;
  stackList: string;
  stackTag: string;
  tab: string;
  tableRow: string;
  tableSection: string;
  tabs: string;
  tabsSlider: string;
  tabsWrap: string;
  taskName: string;
  taskStatus: string;
  title: string;
  titleRow: string;
  titleWrap: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
